# CI: release.yaml
# Context: root
# Requires:
#   - franklyn-proctor-*.tar.gz (build artifact)
#   - proctor/docker/nginx.conf
#   - proctor/docker/entrypoint.sh
FROM nginx:mainline-alpine3.22

ADD ./franklyn-proctor-*.tar.gz /usr/share/nginx/html
COPY proctor/docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY proctor/docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 80
LABEL author="Jakob Huemer-Fistelberger"
