codecov:
  require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 0%
        informational: false
      
      sentinel:
        target: 50%
        threshold: 0%
        paths:
          - "sentinel/"
        informational: false
      
      server:
        target: 60%
        threshold: 0%
        paths:
          - "server/"
        informational: false
      
      proctor:
        paths:
          - "proctor/"
        informational: true

comment:
  layout: "diff, flags, files" 
  behavior: default
  require_changes: true

github_checks:
  annotations: false
