codecov:
  bot: "codecov-io"
  require_ci_to_pass: yes

coverage:
  status:
    project:
      # Overall project coverage: minimum 50% coverage, fails CI if not met
      default:
        target: 50%
        threshold: 0%
        informational: false  # This will fail CI if target not met
      
      # sentinel/ directory: minimum 50% coverage, fails CI if not met
      sentinel:
        target: 50%
        threshold: 0%
        paths:
          - "sentinel/"
        informational: false  # This will fail CI if target not met
      
      # server/ directory: minimum 60% coverage, fails CI if not met
      server:
        target: 60%
        threshold: 0%
        paths:
          - "server/"
        informational: false  # This will fail CI if target not met
      
      # proctor/ directory: reporting only, always passes
      proctor:
        paths:
          - "proctor/"
        informational: true  # This will always pass regardless of coverage


comment:
  layout: "diff, flags, files" 
  behavior: default
  require_changes: true

github_checks:
  annotations: false
