coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 0%
      
      sentinel:
        target: 50%
        threshold: 0%
        flags:
          - sentinel
        
      server:
        target: 50%
        threshold: 0%
        flags:
          - server
      
      proctor:
        target: 50%
        threshold: 0%
        informational: true
        flags:
          - proctor
    
    patch:
      default: off
      
      sentinel:
        target: 50%
        threshold: 0%
        flags:
          - sentinel
      
      server:
        target: 50%
        threshold: 0%
        flags:
          - server
      
      proctor:
        target: 50%
        threshold: 0%
        informational: true
        flags:
          - proctor

flags:
  sentinel:
    paths:
      - "sentinel/"
    carryforward: true
  
  server:
    paths:
      - "server/"
    carryforward: true
  
  proctor:
    paths:
      - "proctor/"
    carryforward: true


comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
