codecov:
  require_ci_to_pass: true


flags:
  sentinel:
    carryforward: true

  server:
    carryforward: true

  proctor:
    carryforward: true


coverage:
  precision: 2
  round: down
  range: "0..100"

  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude

    project:
      default:
        target: 20%
        threshold: 0%
        informational: false

      sentinel:
        flags: [sentinel]
        target: 40%
        threshold: 0%
        informational: false

      server:
        flags: [server]
        target: 10%
        threshold: 0%
        informational: false

      proctor:
        flags: [proctor]
        target: 0%
        threshold: 0%
        informational: false

    patch:
      default:
        target: 0%
        threshold: 0%
        informational: true


comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: true
