codecov:
  require_ci_to_pass: true


flags:
  sentinel:
    carryforward: true

  server:
    carryforward: true

  # proctor:
  #   carryforward: true


coverage:
  precision: 2
  round: down
  range: "0..100"

  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: pass

    project:
      default:
        target: 20%
        threshold: 0%
        informational: true
        flags: 
          - server
          - sentinel
          # - proctor

      sentinel:
        flags: [sentinel]
        target: 40%
        threshold: 0%
        informational: true

      server:
        flags: [server]
        target: 10%
        threshold: 0%
        informational: true

      # proctor:
      #   flags: [proctor]
      #   target: 0%
      #   threshold: 0%
      #   informational: false

    patch:
      default:
        target: 0%
        threshold: 0%
        informational: true

ignore:
  - "server/src/main/java/at/ac/htlleonding/franklynserver/repository/**"

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: true
