// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ws/v2/envelope.proto

package wsv2

import (
	common "github.com/2526-4ahitm-itp/2526-4ahitm-franklyn/server/internal/proto/ws/v2/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Timstamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timstamp,proto3" json:"timstamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Pong
	//	*Envelope_Ping
	//	*Envelope_AuthAck
	//	*Envelope_AuthReject
	//	*Envelope_AuthReq
	//	*Envelope_OpenStream
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_ws_v2_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_ws_v2_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_ws_v2_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetTimstamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timstamp
	}
	return nil
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetPong() *common.Pong {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetPing() *common.Ping {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetAuthAck() *common.AuthAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthAck); ok {
			return x.AuthAck
		}
	}
	return nil
}

func (x *Envelope) GetAuthReject() *common.AuthReject {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthReject); ok {
			return x.AuthReject
		}
	}
	return nil
}

func (x *Envelope) GetAuthReq() *common.AuthReq {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthReq); ok {
			return x.AuthReq
		}
	}
	return nil
}

func (x *Envelope) GetOpenStream() *common.OpenStream {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OpenStream); ok {
			return x.OpenStream
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Pong struct {
	// common messages
	Pong *common.Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *common.Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type Envelope_AuthAck struct {
	// connection
	AuthAck *common.AuthAck `protobuf:"bytes,4,opt,name=auth_ack,json=authAck,proto3,oneof"`
}

type Envelope_AuthReject struct {
	AuthReject *common.AuthReject `protobuf:"bytes,5,opt,name=auth_reject,json=authReject,proto3,oneof"`
}

type Envelope_AuthReq struct {
	AuthReq *common.AuthReq `protobuf:"bytes,6,opt,name=auth_req,json=authReq,proto3,oneof"`
}

type Envelope_OpenStream struct {
	// Stream stuff
	OpenStream *common.OpenStream `protobuf:"bytes,7,opt,name=open_stream,json=openStream,proto3,oneof"`
}

func (*Envelope_Pong) isEnvelope_Payload() {}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_AuthAck) isEnvelope_Payload() {}

func (*Envelope_AuthReject) isEnvelope_Payload() {}

func (*Envelope_AuthReq) isEnvelope_Payload() {}

func (*Envelope_OpenStream) isEnvelope_Payload() {}

var File_ws_v2_envelope_proto protoreflect.FileDescriptor

const file_ws_v2_envelope_proto_rawDesc = "" +
	"\n" +
	"\x14ws/v2/envelope.proto\x12\x05ws.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aws/v2/common/session.proto\x1a\x19ws/v2/common/stream.proto\x1a\x18ws/v2/common/types.proto\"\x83\x03\n" +
	"\bEnvelope\x126\n" +
	"\btimstamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\btimstamp\x12(\n" +
	"\x04pong\x18\x02 \x01(\v2\x12.ws.v2.common.PongH\x00R\x04pong\x12(\n" +
	"\x04ping\x18\x03 \x01(\v2\x12.ws.v2.common.PingH\x00R\x04ping\x122\n" +
	"\bauth_ack\x18\x04 \x01(\v2\x15.ws.v2.common.AuthAckH\x00R\aauthAck\x12;\n" +
	"\vauth_reject\x18\x05 \x01(\v2\x18.ws.v2.common.AuthRejectH\x00R\n" +
	"authReject\x122\n" +
	"\bauth_req\x18\x06 \x01(\v2\x15.ws.v2.common.AuthReqH\x00R\aauthReq\x12;\n" +
	"\vopen_stream\x18\a \x01(\v2\x18.ws.v2.common.OpenStreamH\x00R\n" +
	"openStreamB\t\n" +
	"\apayloadB\xa1\x01\n" +
	"\tcom.ws.v2B\rEnvelopeProtoP\x01ZPgithub.com/2526-4ahitm-itp/2526-4ahitm-franklyn/server/internal/proto/ws/v2;wsv2\xa2\x02\x03WXX\xaa\x02\x05Ws.V2\xca\x02\x05Ws\\V2\xe2\x02\x11Ws\\V2\\GPBMetadata\xea\x02\x06Ws::V2b\x06proto3"

var (
	file_ws_v2_envelope_proto_rawDescOnce sync.Once
	file_ws_v2_envelope_proto_rawDescData []byte
)

func file_ws_v2_envelope_proto_rawDescGZIP() []byte {
	file_ws_v2_envelope_proto_rawDescOnce.Do(func() {
		file_ws_v2_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_v2_envelope_proto_rawDesc), len(file_ws_v2_envelope_proto_rawDesc)))
	})
	return file_ws_v2_envelope_proto_rawDescData
}

var file_ws_v2_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ws_v2_envelope_proto_goTypes = []any{
	(*Envelope)(nil),              // 0: ws.v2.Envelope
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*common.Pong)(nil),           // 2: ws.v2.common.Pong
	(*common.Ping)(nil),           // 3: ws.v2.common.Ping
	(*common.AuthAck)(nil),        // 4: ws.v2.common.AuthAck
	(*common.AuthReject)(nil),     // 5: ws.v2.common.AuthReject
	(*common.AuthReq)(nil),        // 6: ws.v2.common.AuthReq
	(*common.OpenStream)(nil),     // 7: ws.v2.common.OpenStream
}
var file_ws_v2_envelope_proto_depIdxs = []int32{
	1, // 0: ws.v2.Envelope.timstamp:type_name -> google.protobuf.Timestamp
	2, // 1: ws.v2.Envelope.pong:type_name -> ws.v2.common.Pong
	3, // 2: ws.v2.Envelope.ping:type_name -> ws.v2.common.Ping
	4, // 3: ws.v2.Envelope.auth_ack:type_name -> ws.v2.common.AuthAck
	5, // 4: ws.v2.Envelope.auth_reject:type_name -> ws.v2.common.AuthReject
	6, // 5: ws.v2.Envelope.auth_req:type_name -> ws.v2.common.AuthReq
	7, // 6: ws.v2.Envelope.open_stream:type_name -> ws.v2.common.OpenStream
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_ws_v2_envelope_proto_init() }
func file_ws_v2_envelope_proto_init() {
	if File_ws_v2_envelope_proto != nil {
		return
	}
	file_ws_v2_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Pong)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_AuthAck)(nil),
		(*Envelope_AuthReject)(nil),
		(*Envelope_AuthReq)(nil),
		(*Envelope_OpenStream)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_v2_envelope_proto_rawDesc), len(file_ws_v2_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_v2_envelope_proto_goTypes,
		DependencyIndexes: file_ws_v2_envelope_proto_depIdxs,
		MessageInfos:      file_ws_v2_envelope_proto_msgTypes,
	}.Build()
	File_ws_v2_envelope_proto = out.File
	file_ws_v2_envelope_proto_goTypes = nil
	file_ws_v2_envelope_proto_depIdxs = nil
}
