# CI: hugo-deploy.yaml
# Context: root
# Requires:
#   - hugo/public-docker (built locally)
#   - hugo/docker/nginx.conf
FROM nginx:mainline-alpine3.22

COPY hugo/public-docker /usr/share/nginx/html
COPY hugo/docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
LABEL author="Jakob Huemer-Fistelberger"
