server {
    listen 80;

    root /usr/share/nginx/html;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    location ~ ^/de/(.+)$ {
        set $de_path $1;
        try_files $uri $uri/ @de_fallback;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location @de_fallback {
        return 302 /$de_path;
    }
}