// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FrNoticeType string

const (
	FrNoticeTypeAlert  FrNoticeType = "alert"
	FrNoticeTypeTimed  FrNoticeType = "timed"
	FrNoticeTypeSingle FrNoticeType = "single"
)

func (e *FrNoticeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrNoticeType(s)
	case string:
		*e = FrNoticeType(s)
	default:
		return fmt.Errorf("unsupported scan type for FrNoticeType: %T", src)
	}
	return nil
}

type NullFrNoticeType struct {
	FrNoticeType FrNoticeType `json:"frNoticeType"`
	Valid        bool         `json:"valid"` // Valid is true if FrNoticeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrNoticeType) Scan(value interface{}) error {
	if value == nil {
		ns.FrNoticeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrNoticeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrNoticeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrNoticeType), nil
}

type FrSettingsTheme string

const (
	FrSettingsThemeLight  FrSettingsTheme = "light"
	FrSettingsThemeDark   FrSettingsTheme = "dark"
	FrSettingsThemeSystem FrSettingsTheme = "system"
)

func (e *FrSettingsTheme) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrSettingsTheme(s)
	case string:
		*e = FrSettingsTheme(s)
	default:
		return fmt.Errorf("unsupported scan type for FrSettingsTheme: %T", src)
	}
	return nil
}

type NullFrSettingsTheme struct {
	FrSettingsTheme FrSettingsTheme `json:"frSettingsTheme"`
	Valid           bool            `json:"valid"` // Valid is true if FrSettingsTheme is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrSettingsTheme) Scan(value interface{}) error {
	if value == nil {
		ns.FrSettingsTheme, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrSettingsTheme.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrSettingsTheme) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrSettingsTheme), nil
}

type FrUserType string

const (
	FrUserTypeTEACHER FrUserType = "TEACHER"
	FrUserTypeSTUDENT FrUserType = "STUDENT"
)

func (e *FrUserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrUserType(s)
	case string:
		*e = FrUserType(s)
	default:
		return fmt.Errorf("unsupported scan type for FrUserType: %T", src)
	}
	return nil
}

type NullFrUserType struct {
	FrUserType FrUserType `json:"frUserType"`
	Valid      bool       `json:"valid"` // Valid is true if FrUserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrUserType) Scan(value interface{}) error {
	if value == nil {
		ns.FrUserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrUserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrUserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrUserType), nil
}

type FrExam struct {
	ID        uuid.UUID        `json:"id"`
	TeacherID *uuid.UUID       `json:"teacherId"`
	Title     string           `json:"title"`
	Pin       int16            `json:"pin"`
	StartTime pgtype.Timestamp `json:"startTime"`
	EndTime   pgtype.Timestamp `json:"endTime"`
	StartedAt pgtype.Timestamp `json:"startedAt"`
	EndedAt   pgtype.Timestamp `json:"endedAt"`
}

type FrExamSession struct {
	StudentID     uuid.UUID   `json:"studentId"`
	SentinelID    uuid.UUID   `json:"sentinelId"`
	ExamID        uuid.UUID   `json:"examId"`
	VideoFilePath pgtype.Text `json:"videoFilePath"`
	VideoStatus   pgtype.Text `json:"videoStatus"`
}

type FrNotice struct {
	ID        uuid.UUID        `json:"id"`
	Type      FrNoticeType     `json:"type"`
	Content   string           `json:"content"`
	StartTime pgtype.Timestamp `json:"startTime"`
	EndTime   pgtype.Timestamp `json:"endTime"`
}

type FrStudent struct {
	ID uuid.UUID `json:"id"`
}

type FrTeacher struct {
	ID uuid.UUID `json:"id"`
}

type FrUser struct {
	ID                uuid.UUID           `json:"id"`
	PreferredUsername string              `json:"preferredUsername"`
	Email             string              `json:"email"`
	GivenName         pgtype.Text         `json:"givenName"`
	FamilyName        pgtype.Text         `json:"familyName"`
	Theme             NullFrSettingsTheme `json:"theme"`
	Language          pgtype.Text         `json:"language"`
	Role              FrUserType          `json:"role"`
}
