// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FrNoticeType string

const (
	FrNoticeTypeAlert  FrNoticeType = "alert"
	FrNoticeTypeTimed  FrNoticeType = "timed"
	FrNoticeTypeSingle FrNoticeType = "single"
)

func (e *FrNoticeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrNoticeType(s)
	case string:
		*e = FrNoticeType(s)
	default:
		return fmt.Errorf("unsupported scan type for FrNoticeType: %T", src)
	}
	return nil
}

type NullFrNoticeType struct {
	FrNoticeType FrNoticeType
	Valid        bool // Valid is true if FrNoticeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrNoticeType) Scan(value interface{}) error {
	if value == nil {
		ns.FrNoticeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrNoticeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrNoticeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrNoticeType), nil
}

type FrSettingsTheme string

const (
	FrSettingsThemeLight  FrSettingsTheme = "light"
	FrSettingsThemeDark   FrSettingsTheme = "dark"
	FrSettingsThemeSystem FrSettingsTheme = "system"
)

func (e *FrSettingsTheme) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrSettingsTheme(s)
	case string:
		*e = FrSettingsTheme(s)
	default:
		return fmt.Errorf("unsupported scan type for FrSettingsTheme: %T", src)
	}
	return nil
}

type NullFrSettingsTheme struct {
	FrSettingsTheme FrSettingsTheme
	Valid           bool // Valid is true if FrSettingsTheme is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrSettingsTheme) Scan(value interface{}) error {
	if value == nil {
		ns.FrSettingsTheme, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrSettingsTheme.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrSettingsTheme) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrSettingsTheme), nil
}

type FrUserType string

const (
	FrUserTypeTEACHER FrUserType = "TEACHER"
	FrUserTypeSTUDENT FrUserType = "STUDENT"
)

func (e *FrUserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrUserType(s)
	case string:
		*e = FrUserType(s)
	default:
		return fmt.Errorf("unsupported scan type for FrUserType: %T", src)
	}
	return nil
}

type NullFrUserType struct {
	FrUserType FrUserType
	Valid      bool // Valid is true if FrUserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrUserType) Scan(value interface{}) error {
	if value == nil {
		ns.FrUserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrUserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrUserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrUserType), nil
}

type FrExam struct {
	ID        uuid.UUID
	TeacherID *uuid.UUID
	Title     string
	Pin       int16
	StartTime pgtype.Timestamp
	EndTime   pgtype.Timestamp
	StartedAt pgtype.Timestamp
	EndedAt   pgtype.Timestamp
}

type FrExamSession struct {
	StudentID     uuid.UUID
	SentinelID    uuid.UUID
	ExamID        uuid.UUID
	VideoFilePath pgtype.Text
	VideoStatus   pgtype.Text
}

type FrNotice struct {
	ID        uuid.UUID
	Type      FrNoticeType
	Content   string
	StartTime pgtype.Timestamp
	EndTime   pgtype.Timestamp
}

type FrStudent struct {
	ID uuid.UUID
}

type FrTeacher struct {
	ID uuid.UUID
}

type FrUser struct {
	ID                uuid.UUID
	PreferredUsername string
	Email             string
	GivenName         pgtype.Text
	FamilyName        pgtype.Text
	Theme             NullFrSettingsTheme
	Language          pgtype.Text
	Role              FrUserType
}
