// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notice.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotice = `-- name: CreateNotice :one
insert into fr_notice (id, type, content, start_time, end_time)
values (uuidv7(), $1, $2, $3, $4)
returning id, type, content, start_time, end_time
`

type CreateNoticeParams struct {
	Type      FrNoticeType     `json:"type"`
	Content   string           `json:"content"`
	StartTime pgtype.Timestamp `json:"startTime"`
	EndTime   pgtype.Timestamp `json:"endTime"`
}

func (q *Queries) CreateNotice(ctx context.Context, arg CreateNoticeParams) (FrNotice, error) {
	row := q.db.QueryRow(ctx, createNotice,
		arg.Type,
		arg.Content,
		arg.StartTime,
		arg.EndTime,
	)
	var i FrNotice
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Content,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteNotice = `-- name: DeleteNotice :exec
delete from fr_notice
where id = $1
`

func (q *Queries) DeleteNotice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotice, id)
	return err
}

const getNoticeById = `-- name: GetNoticeById :one
select id, type, content, start_time, end_time from fr_notice
where id = $1
`

func (q *Queries) GetNoticeById(ctx context.Context, id uuid.UUID) (FrNotice, error) {
	row := q.db.QueryRow(ctx, getNoticeById, id)
	var i FrNotice
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Content,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const getNotices = `-- name: GetNotices :many
select id, type, content, start_time, end_time from fr_notice
`

func (q *Queries) GetNotices(ctx context.Context) ([]FrNotice, error) {
	rows, err := q.db.Query(ctx, getNotices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FrNotice{}
	for rows.Next() {
		var i FrNotice
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Content,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotice = `-- name: UpdateNotice :one
update fr_notice set
    content = $2,
    start_time = $3,
    end_time = $4
where id = $1
returning id, type, content, start_time, end_time
`

type UpdateNoticeParams struct {
	ID        uuid.UUID        `json:"id"`
	Content   string           `json:"content"`
	StartTime pgtype.Timestamp `json:"startTime"`
	EndTime   pgtype.Timestamp `json:"endTime"`
}

func (q *Queries) UpdateNotice(ctx context.Context, arg UpdateNoticeParams) (FrNotice, error) {
	row := q.db.QueryRow(ctx, updateNotice,
		arg.ID,
		arg.Content,
		arg.StartTime,
		arg.EndTime,
	)
	var i FrNotice
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Content,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}
