main:
  - identifier: resources
    name: Developer
    weight: 10
  - name: Documentation
    pageRef: /docs
    parent: resources
    weight: 11
  - name: Project
    pageRef: /project
    parent: resources
    weight: 12
  - name: Diagrams
    pageRef: /diagrams
    parent: resources
    weight: 13
  - name: Releases
    pageRef: /releases
    weight: 25
  - name: Guide
    pageRef: /guide
    weight: 30
  - identifier: proctor
    name: Proctor
    url: /proctor
    weight: 40
  - identifier: glitchtip
    name: Sentry
    url: /glitchtip
    weight: 45
  - name: Search
    weight: 50
    params:
      type: search
  - name: GitHub
    weight: 60
    url: "https://github.com/2526-4ahitm-itp/2526-4ahitm-franklyn"
    params:
      icon: github
