version: '3.8'

services:
  postgres:
    image: postgres:18
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - franklyn-postgres-database:/var/lib/postgresql
    networks:
      - franklyn-network

  #   adminer:
  #     image: elestio/pgadmin
  #     restart: always
  #     environment:
  #       PGADMIN_LISTEN_PORT: 8080
  #       PGADMIN_DEFAULT_EMAIL: admin@example.com
  #       PGADMIN_DEFAULT_PASSWORD: admin
  #       PGADMIN_CONFIG_SERVER_MODE: 'False'
  #     ports:
  #       - "8080:8080"
  #     volumes:
  #       - ./servers.json:/pgadmin4/servers.json
  pgadmin:
    image: "dpage/pgadmin4"
    container_name: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mycomp.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    links:
      - postgres:postgres
    ports:
      - 9090:80
    networks:
      - franklyn-network
    volumes:
      - franklyn-pgadmin4-servers:/var/lib/pgadmin

volumes:
  franklyn-postgres-database:
  franklyn-pgadmin4-servers:


networks:
  franklyn-network:
    driver: bridge
