services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-dev
    environment:
      # Admin credentials
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      
      # Development mode settings
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
    
    command:
      - start-dev
      - --import-realm
    
    volumes:
      # - franklyn-keycloak-data:/opt/keycloak/data
      - ./realm.json:/opt/keycloak/data/import/realm.json:ro
    
    ports:
      - "7070:8080"
    
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s

    
    networks:
      - franklyn-network

volumes:
  franklyn-keycloak-data:
