services:
  franklyn-server:
    image: ghcr.io/2526-4ahitm-itp/franklyn-server:latest
    container_name: franklyn-server
    # environment:
    #   QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/db
    #   QUARKUS_DATASOURCE_USERNAME: app
    #   QUARKUS_DATASOURCE_PASSWORD: app
    networks:
      - franklyn
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8080/api/q/health" ]
      interval: 5s
      timeout: 5s
      retries: 10

  franklyn-proctor:
    image: ghcr.io/2526-4ahitm-itp/franklyn-proctor:latest
    container_name: franklyn-proctor
    networks:
      - franklyn
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost/proctor" ]
      interval: 5s
      timeout: 5s
      retries: 10

  franklyn-hugo:
    image: ghcr.io/2526-4ahitm-itp/franklyn-hugo:latest
    container_name: franklyn-hugo
    networks:
      - franklyn
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost/" ]
      interval: 5s
      timeout: 5s
      retries: 10
