services:
  caddy:
    image: caddy:2-alpine
    container_name: franklyn-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - franklyn
    # healthcheck:
    #   test: [ "CMD", "wget", "-q", "--spider", "http://localhost:2019/config/" ]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10

volumes:
  caddy_data:
  caddy_config:
