services:
  franklyn-server:
    image: ghcr.io/2526-4ahitm-itp/franklyn-server:dev
    container_name: franklyn-server
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FRANKLYN_STORAGE_DIR: ${FRANKLYN_STORAGE_DIR}
      KEYCLOAK_URL: ${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID_SERVER}
    networks:
      - franklyn
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8080/api/q/health" ]
      interval: 5s
      timeout: 5s
      retries: 10

  franklyn-proctor:
    image: ghcr.io/2526-4ahitm-itp/franklyn-proctor:dev
    container_name: franklyn-proctor
    environment:
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID_PROCTOR}
      FRANKLYN_TELEMETRY: ${FRANKLYN_TELEMETRY}
    networks:
      - franklyn
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost/proctor" ]
      interval: 5s
      timeout: 5s
      retries: 10

  franklyn-hugo:
    image: ghcr.io/2526-4ahitm-itp/franklyn-hugo:latest
    container_name: franklyn-hugo
    networks:
      - franklyn
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost/" ]
      interval: 5s
      timeout: 5s
      retries: 10
