// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package store

import (
	"context"
)

const getUsers = `-- name: GetUsers :many
select id, preferred_username, email, given_name, family_name, theme, language, role from fr_user
`

func (q *Queries) GetUsers(ctx context.Context) ([]FrUser, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FrUser
	for rows.Next() {
		var i FrUser
		if err := rows.Scan(
			&i.ID,
			&i.PreferredUsername,
			&i.Email,
			&i.GivenName,
			&i.FamilyName,
			&i.Theme,
			&i.Language,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
