# CI: release.yaml
# Context: root
# requires:
#   - franklyn-server-go-* arch binary from ci
FROM docker.io/alpine:latest
WORKDIR /opt/franklyn-server

ARG TARGETARCH

COPY --chmod=0755 ./franklyn-server-go-*-${TARGETARCH} ./server

EXPOSE 8080
LABEL author="Jakob Huemer-Fistelberger"

ENTRYPOINT [ "./server" ]
