// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//   sqlc-gen-java 0.0.7

package at.ac.htlleonding.franklynserver.repository;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

@Generated("io.github.tandemdude.sqlc-gen-java")
public class RecordingQueries {
    private final java.sql.Connection conn;

    public RecordingQueries(java.sql.Connection conn) {
        this.conn = conn;
    }

    private static @Nullable Long getLong(@NonNull ResultSet rs, int col) throws SQLException {
        var colVal = rs.getLong(col); return rs.wasNull() ? null : colVal;
    }

    private static final String findAllRecordings = """
        -- name: findAllRecordings :many
        select end_time, id, start_time, test_id, pc_name, student_name, video_file from fr_test_recording
        """;

    public record FindAllRecordingsRow(
        @Nullable LocalDateTime endTime,
        long id,
        @Nullable LocalDateTime startTime,
        @Nullable Long testId,
        @Nullable String pcName,
        @Nullable String studentName,
        @Nullable String videoFile
    ) {}

    public List<FindAllRecordingsRow> findAllRecordings() throws SQLException {
        var stmt = conn.prepareStatement(findAllRecordings);

        var results = stmt.executeQuery();
        var retList = new ArrayList<FindAllRecordingsRow>();
        while (results.next()) {
            var ret = new FindAllRecordingsRow(
                results.getObject(1, LocalDateTime.class),
                results.getLong(2),
                results.getObject(3, LocalDateTime.class),
                getLong(results, 4),
                results.getString(5),
                results.getString(6),
                results.getString(7)
            );
            retList.add(ret);
        }

        return retList;
    }

    private static final String findRecordingById = """
        -- name: findRecordingById :one
        select end_time, id, start_time, test_id, pc_name, student_name, video_file from fr_test_recording
        where id = ?
        """;

    public record FindRecordingByIdRow(
        @Nullable LocalDateTime endTime,
        long id,
        @Nullable LocalDateTime startTime,
        @Nullable Long testId,
        @Nullable String pcName,
        @Nullable String studentName,
        @Nullable String videoFile
    ) {}

    public Optional<FindRecordingByIdRow> findRecordingById(
        long id
    ) throws SQLException {
        var stmt = conn.prepareStatement(findRecordingById);
        stmt.setLong(1, id);

        var results = stmt.executeQuery();
        if (!results.next()) {
            return Optional.empty();
        }

        var ret = new FindRecordingByIdRow(
            results.getObject(1, LocalDateTime.class),
            results.getLong(2),
            results.getObject(3, LocalDateTime.class),
            getLong(results, 4),
            results.getString(5),
            results.getString(6),
            results.getString(7)
        );
        if (results.next()) {
            throw new SQLException("expected one row in result set, but got many");
        }

        return Optional.of(ret);
    }

    private static final String insertRecording = """
        -- name: insertRecording :exec
        insert into fr_test_recording (end_time, id, start_time, test_id, pc_name, student_name, video_file)
        values (?, ?, ?, ?, ?, ?, ?)
        """;

    public void insertRecording(
        @Nullable LocalDateTime endTime,
        long id,
        @Nullable LocalDateTime startTime,
        @Nullable Long testId,
        @Nullable String pcName,
        @Nullable String studentName,
        @Nullable String videoFile
    ) throws SQLException {
        var stmt = conn.prepareStatement(insertRecording);
        stmt.setObject(1, endTime);
        stmt.setLong(2, id);
        stmt.setObject(3, startTime);
        
		if (testId != null) {
		    stmt.setLong(4, testId);
		} else {
		    stmt.setNull(4, java.sql.Types.BIGINT);
		}
		
        stmt.setString(5, pcName);
        stmt.setString(6, studentName);
        stmt.setString(7, videoFile);

        stmt.execute();
    }
}
