// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//   sqlc-gen-java 0.0.7

package at.ac.htlleonding.franklynserver.repository;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

@Generated("io.github.tandemdude.sqlc-gen-java")
public class TeacherQueries {
    private final java.sql.Connection conn;

    public TeacherQueries(java.sql.Connection conn) {
        this.conn = conn;
    }

    private static @Nullable Long getLong(@NonNull ResultSet rs, int col) throws SQLException {
        var colVal = rs.getLong(col); return rs.wasNull() ? null : colVal;
    }

    private static final String findAllTeachers = """
        -- name: findAllTeachers :many
        select id, name from fr_teacher
        """;

    public record FindAllTeachersRow(
        long id,
        @Nullable String name
    ) {}

    public List<FindAllTeachersRow> findAllTeachers() throws SQLException {
        var stmt = conn.prepareStatement(findAllTeachers);

        var results = stmt.executeQuery();
        var retList = new ArrayList<FindAllTeachersRow>();
        while (results.next()) {
            var ret = new FindAllTeachersRow(
                results.getLong(1),
                results.getString(2)
            );
            retList.add(ret);
        }

        return retList;
    }

    private static final String findTeacherById = """
        -- name: findTeacherById :one
        select id, name from fr_teacher
        where id = ?
        """;

    public record FindTeacherByIdRow(
        long id,
        @Nullable String name
    ) {}

    public Optional<FindTeacherByIdRow> findTeacherById(
        long id
    ) throws SQLException {
        var stmt = conn.prepareStatement(findTeacherById);
        stmt.setLong(1, id);

        var results = stmt.executeQuery();
        if (!results.next()) {
            return Optional.empty();
        }

        var ret = new FindTeacherByIdRow(
            results.getLong(1),
            results.getString(2)
        );
        if (results.next()) {
            throw new SQLException("expected one row in result set, but got many");
        }

        return Optional.of(ret);
    }

    private static final String insertTeacher = """
        -- name: insertTeacher :exec
        insert into fr_teacher (id, name)
        values (?, ?)
        """;

    public void insertTeacher(
        long id,
        @Nullable String name
    ) throws SQLException {
        var stmt = conn.prepareStatement(insertTeacher);
        stmt.setLong(1, id);
        stmt.setString(2, name);

        stmt.execute();
    }
}
