// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//   sqlc-gen-java 0.0.7

package at.ac.htlleonding.franklynserver.repository;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

@Generated("io.github.tandemdude.sqlc-gen-java")
public class TestQueries {
    private final java.sql.Connection conn;

    public TestQueries(java.sql.Connection conn) {
        this.conn = conn;
    }

    private static @Nullable Long getLong(@NonNull ResultSet rs, int col) throws SQLException {
        var colVal = rs.getLong(col); return rs.wasNull() ? null : colVal;
    }

    private static final String findAllTests = """
        -- name: findAllTests :many
        select id, teacher_id, title, test_account_prefix, end_time, start_time from fr_test
        """;

    public record FindAllTestsRow(
        long id,
        @Nullable Long teacherId,
        @NonNull String title,
        @Nullable String testAccountPrefix,
        @Nullable LocalDateTime endTime,
        @Nullable LocalDateTime startTime
    ) {}

    public List<FindAllTestsRow> findAllTests() throws SQLException {
        var stmt = conn.prepareStatement(findAllTests);

        var results = stmt.executeQuery();
        var retList = new ArrayList<FindAllTestsRow>();
        while (results.next()) {
            var ret = new FindAllTestsRow(
                results.getLong(1),
                getLong(results, 2),
                results.getString(3),
                results.getString(4),
                results.getObject(5, LocalDateTime.class),
                results.getObject(6, LocalDateTime.class)
            );
            retList.add(ret);
        }

        return retList;
    }

    private static final String findTestById = """
        -- name: findTestById :one
        select id, teacher_id, title, test_account_prefix, end_time, start_time from fr_test
        where id = ?
        """;

    public record FindTestByIdRow(
        long id,
        @Nullable Long teacherId,
        @NonNull String title,
        @Nullable String testAccountPrefix,
        @Nullable LocalDateTime endTime,
        @Nullable LocalDateTime startTime
    ) {}

    public Optional<FindTestByIdRow> findTestById(
        long id
    ) throws SQLException {
        var stmt = conn.prepareStatement(findTestById);
        stmt.setLong(1, id);

        var results = stmt.executeQuery();
        if (!results.next()) {
            return Optional.empty();
        }

        var ret = new FindTestByIdRow(
            results.getLong(1),
            getLong(results, 2),
            results.getString(3),
            results.getString(4),
            results.getObject(5, LocalDateTime.class),
            results.getObject(6, LocalDateTime.class)
        );
        if (results.next()) {
            throw new SQLException("expected one row in result set, but got many");
        }

        return Optional.of(ret);
    }

    private static final String insertTest = """
        -- name: insertTest :exec
        insert into fr_test (id, teacher_id, title, test_account_prefix, end_time, start_time)
        values (?, ?, ?, ?, ?, ?)
        """;

    public void insertTest(
        long id,
        @Nullable Long teacherId,
        @NonNull String title,
        @Nullable String testAccountPrefix,
        @Nullable LocalDateTime endTime,
        @Nullable LocalDateTime startTime
    ) throws SQLException {
        var stmt = conn.prepareStatement(insertTest);
        stmt.setLong(1, id);
        
		if (teacherId != null) {
		    stmt.setLong(2, teacherId);
		} else {
		    stmt.setNull(2, java.sql.Types.BIGINT);
		}
		
        stmt.setString(3, title);
        stmt.setString(4, testAccountPrefix);
        stmt.setObject(5, endTime);
        stmt.setObject(6, startTime);

        stmt.execute();
    }
}
