// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ws/v2/common/session.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_ws_v2_common_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_ws_v2_common_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_ws_v2_common_session_proto_rawDescGZIP(), []int{0}
}

func (x *AuthReq) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type AuthAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *UUID                  `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthAck) Reset() {
	*x = AuthAck{}
	mi := &file_ws_v2_common_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAck) ProtoMessage() {}

func (x *AuthAck) ProtoReflect() protoreflect.Message {
	mi := &file_ws_v2_common_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthAck.ProtoReflect.Descriptor instead.
func (*AuthAck) Descriptor() ([]byte, []int) {
	return file_ws_v2_common_session_proto_rawDescGZIP(), []int{1}
}

func (x *AuthAck) GetClientId() *UUID {
	if x != nil {
		return x.ClientId
	}
	return nil
}

type AuthReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReject) Reset() {
	*x = AuthReject{}
	mi := &file_ws_v2_common_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReject) ProtoMessage() {}

func (x *AuthReject) ProtoReflect() protoreflect.Message {
	mi := &file_ws_v2_common_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReject.ProtoReflect.Descriptor instead.
func (*AuthReject) Descriptor() ([]byte, []int) {
	return file_ws_v2_common_session_proto_rawDescGZIP(), []int{2}
}

func (x *AuthReject) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthReject) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_ws_v2_common_session_proto protoreflect.FileDescriptor

const file_ws_v2_common_session_proto_rawDesc = "" +
	"\n" +
	"\x1aws/v2/common/session.proto\x12\fws.v2.common\x1a\x18ws/v2/common/types.proto\"\x1b\n" +
	"\aAuthReq\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\":\n" +
	"\aAuthAck\x12/\n" +
	"\tclient_id\x18\x01 \x01(\v2\x12.ws.v2.common.UUIDR\bclientId\"8\n" +
	"\n" +
	"AuthReject\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB\xc6\x01\n" +
	"\x10com.ws.v2.commonB\fSessionProtoP\x01ZRgithub.com/2526-4ahitm-itp/2526-4ahitm-franklyn/server/internal/proto/ws/v2/common\xa2\x02\x03WVC\xaa\x02\fWs.V2.Common\xca\x02\fWs\\V2\\Common\xe2\x02\x18Ws\\V2\\Common\\GPBMetadata\xea\x02\x0eWs::V2::Commonb\x06proto3"

var (
	file_ws_v2_common_session_proto_rawDescOnce sync.Once
	file_ws_v2_common_session_proto_rawDescData []byte
)

func file_ws_v2_common_session_proto_rawDescGZIP() []byte {
	file_ws_v2_common_session_proto_rawDescOnce.Do(func() {
		file_ws_v2_common_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_v2_common_session_proto_rawDesc), len(file_ws_v2_common_session_proto_rawDesc)))
	})
	return file_ws_v2_common_session_proto_rawDescData
}

var file_ws_v2_common_session_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ws_v2_common_session_proto_goTypes = []any{
	(*AuthReq)(nil),    // 0: ws.v2.common.AuthReq
	(*AuthAck)(nil),    // 1: ws.v2.common.AuthAck
	(*AuthReject)(nil), // 2: ws.v2.common.AuthReject
	(*UUID)(nil),       // 3: ws.v2.common.UUID
}
var file_ws_v2_common_session_proto_depIdxs = []int32{
	3, // 0: ws.v2.common.AuthAck.client_id:type_name -> ws.v2.common.UUID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ws_v2_common_session_proto_init() }
func file_ws_v2_common_session_proto_init() {
	if File_ws_v2_common_session_proto != nil {
		return
	}
	file_ws_v2_common_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_v2_common_session_proto_rawDesc), len(file_ws_v2_common_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_v2_common_session_proto_goTypes,
		DependencyIndexes: file_ws_v2_common_session_proto_depIdxs,
		MessageInfos:      file_ws_v2_common_session_proto_msgTypes,
	}.Build()
	File_ws_v2_common_session_proto = out.File
	file_ws_v2_common_session_proto_goTypes = nil
	file_ws_v2_common_session_proto_depIdxs = nil
}
