// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ws/v2/common/stream.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      *UUID                  `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StreamMeta    *StreamMeta            `protobuf:"bytes,2,opt,name=stream_meta,json=streamMeta,proto3" json:"stream_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStream) Reset() {
	*x = OpenStream{}
	mi := &file_ws_v2_common_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStream) ProtoMessage() {}

func (x *OpenStream) ProtoReflect() protoreflect.Message {
	mi := &file_ws_v2_common_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStream.ProtoReflect.Descriptor instead.
func (*OpenStream) Descriptor() ([]byte, []int) {
	return file_ws_v2_common_stream_proto_rawDescGZIP(), []int{0}
}

func (x *OpenStream) GetStreamId() *UUID {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *OpenStream) GetStreamMeta() *StreamMeta {
	if x != nil {
		return x.StreamMeta
	}
	return nil
}

type StreamMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Something     string                 `protobuf:"bytes,1,opt,name=something,proto3" json:"something,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMeta) Reset() {
	*x = StreamMeta{}
	mi := &file_ws_v2_common_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMeta) ProtoMessage() {}

func (x *StreamMeta) ProtoReflect() protoreflect.Message {
	mi := &file_ws_v2_common_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMeta.ProtoReflect.Descriptor instead.
func (*StreamMeta) Descriptor() ([]byte, []int) {
	return file_ws_v2_common_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamMeta) GetSomething() string {
	if x != nil {
		return x.Something
	}
	return ""
}

var File_ws_v2_common_stream_proto protoreflect.FileDescriptor

const file_ws_v2_common_stream_proto_rawDesc = "" +
	"\n" +
	"\x19ws/v2/common/stream.proto\x12\fws.v2.common\x1a\x18ws/v2/common/types.proto\"x\n" +
	"\n" +
	"OpenStream\x12/\n" +
	"\tstream_id\x18\x01 \x01(\v2\x12.ws.v2.common.UUIDR\bstreamId\x129\n" +
	"\vstream_meta\x18\x02 \x01(\v2\x18.ws.v2.common.StreamMetaR\n" +
	"streamMeta\"*\n" +
	"\n" +
	"StreamMeta\x12\x1c\n" +
	"\tsomething\x18\x01 \x01(\tR\tsomethingB\xc5\x01\n" +
	"\x10com.ws.v2.commonB\vStreamProtoP\x01ZRgithub.com/2526-4ahitm-itp/2526-4ahitm-franklyn/server/internal/proto/ws/v2/common\xa2\x02\x03WVC\xaa\x02\fWs.V2.Common\xca\x02\fWs\\V2\\Common\xe2\x02\x18Ws\\V2\\Common\\GPBMetadata\xea\x02\x0eWs::V2::Commonb\x06proto3"

var (
	file_ws_v2_common_stream_proto_rawDescOnce sync.Once
	file_ws_v2_common_stream_proto_rawDescData []byte
)

func file_ws_v2_common_stream_proto_rawDescGZIP() []byte {
	file_ws_v2_common_stream_proto_rawDescOnce.Do(func() {
		file_ws_v2_common_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_v2_common_stream_proto_rawDesc), len(file_ws_v2_common_stream_proto_rawDesc)))
	})
	return file_ws_v2_common_stream_proto_rawDescData
}

var file_ws_v2_common_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ws_v2_common_stream_proto_goTypes = []any{
	(*OpenStream)(nil), // 0: ws.v2.common.OpenStream
	(*StreamMeta)(nil), // 1: ws.v2.common.StreamMeta
	(*UUID)(nil),       // 2: ws.v2.common.UUID
}
var file_ws_v2_common_stream_proto_depIdxs = []int32{
	2, // 0: ws.v2.common.OpenStream.stream_id:type_name -> ws.v2.common.UUID
	1, // 1: ws.v2.common.OpenStream.stream_meta:type_name -> ws.v2.common.StreamMeta
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ws_v2_common_stream_proto_init() }
func file_ws_v2_common_stream_proto_init() {
	if File_ws_v2_common_stream_proto != nil {
		return
	}
	file_ws_v2_common_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_v2_common_stream_proto_rawDesc), len(file_ws_v2_common_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_v2_common_stream_proto_goTypes,
		DependencyIndexes: file_ws_v2_common_stream_proto_depIdxs,
		MessageInfos:      file_ws_v2_common_stream_proto_msgTypes,
	}.Build()
	File_ws_v2_common_stream_proto = out.File
	file_ws_v2_common_stream_proto_goTypes = nil
	file_ws_v2_common_stream_proto_depIdxs = nil
}
